(TeX-add-style-hook
 "estatistica1"
 (lambda ()
   (TeX-add-symbols
    "chapterillustration"
    "chapterwhat"
    "chapterbecause")
   (LaTeX-add-index-entries
    "Estatística|textbf"
    "frequência"
    "amplitude"
    "Amplitude|textbf"
    "dispersão"
    "Dispersão|textbf"
    "Amostra"
    "amostra"
    "população"
    "variáveis"
    "elemento"
    "variável"
    "infográficos"
    "infográfico"
    "Amostra|textbf"
    "Parâmetro|textbf"
    "Estimador|textbf"
    "Estatística Descritiva"
    "Estatística Inferencial"
    "censo"
    "Variável qualitativa|textbf"
    "Variável qualitativa nominal|textbf"
    "Variável qualitativa ordinal|textbf"
    "Variável quantitativa|textbf"
    "Variável quantitativa discreta|textbf"
    "Variável quantitativa contínua|textbf"
    "variável binária"
    "gráfico de barras"
    "frequência absoluta"
    "frequência relativa"
    "gráficos de barras múltiplas"
    "gráfico de setores"
    "gráficos de retângulos"
    "histograma"
    "séries temporais"
    "gráficos de linha"
    "sazonalidade"
    "Sazonalidade|textbf"
    "Histograma|textbf"
    "Gráfico de linha|textbf"
    "amostragem aleatória simples"
    "amostragem estratificada"
    "amostragem por coglomerados"
    "amostragem sitemática"
    "amostragem por conveniência"
    "amostragem por julgamento"
    "mediana"))
 :latex)

